name: SparkleClient
targets:
  SparkleClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [SparkleClient]
    info:
      path: ./Info.plist
      version: 0.0.2
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: Alamofire
    - carthage: RxSwift
