//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RxSwift



open class DefaultAPI {
    /**
     メッセージを送信します。
     
     - parameter text: (query) The number of items to skip before starting to collect the result set (optional)
     - returns: Observable<Void>
     */
    open class func addMessagePost(text: String? = nil) -> Observable<Void> {
        return Observable.create { observer -> Disposable in
            addMessagePostWithRequestBuilder(text: text).execute { (response, error) -> Void in
                if let error = error {
                    observer.onError(error)
                } else {
                    observer.onNext(())
                }
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }

    /**
     メッセージを送信します。
     - POST /addMessage
     - サーバーの状態を返します。
     - parameter text: (query) The number of items to skip before starting to collect the result set (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func addMessagePostWithRequestBuilder(text: String? = nil) -> RequestBuilder<Void> {
        let path = "/addMessage"
        let URLString = SparkleAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "text": text?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<Void>.Type = SparkleAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
