//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RxSwift



open class UsersAPI {
    /**
     メッセージを取得します
     
     - returns: Observable<[User]>
     */
    open class func getMessagesGet() -> Observable<[User]> {
        return Observable.create { observer -> Disposable in
            getMessagesGetWithRequestBuilder().execute { (response, error) -> Void in
                if let error = error {
                    observer.onError(error)
                } else if let response = response {
                    observer.onNext(response.body!)
                } else {
                    fatalError()
                }
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }

    /**
     メッセージを取得します
     - GET /getMessages
     - メッセージの取得
     - returns: RequestBuilder<[User]> 
     */
    open class func getMessagesGetWithRequestBuilder() -> RequestBuilder<[User]> {
        let path = "/getMessages"
        let URLString = SparkleAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[User]>.Type = SparkleAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
