//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ユーザーモデル */
public struct User: Codable { 


    public var id: Int64?
    public var name: String?
    public var avatarUrl: String?

    public init(id: Int64?, name: String?, avatarUrl: String?) {
        self.id = id
        self.name = name
        self.avatarUrl = avatarUrl
    }

}
